import {
  PaymentOptionsDBType,
  SocialPlatformsDBType,
} from "@/types/enum.types";

export const usCitiesOptions = [
  "Albuquerque",
  "Arlington",
  "Atlanta",
  "Austin",
  "Baltimore",
  "Boston",
  "Charlotte",
  "Chicago",
  "Cleveland",
  "Colorado Springs",
  "Columbus",
  "Dallas",
  "Denver",
  "Detroit",
  "El Paso",
  "Fort Worth",
  "Fresno",
  "Houston",
  "Indianapolis",
  "Jacksonville",
  "Kansas City",
  "Las Vegas",
  "Los Angeles",
  "Louisville",
  "Memphis",
  "Mesa",
  "Miami",
  "Milwaukee",
  "Minneapolis",
  "Nashville",
  "New Orleans",
  "New York",
  "Oakland",
  "Oklahoma City",
  "Omaha",
  "Philadelphia",
  "Phoenix",
  "Portland",
  "Raleigh",
  "Sacramento",
  "San Antonio",
  "San Diego",
  "San Francisco",
  "San Jose",
  "Seattle",
  "Tulsa",
  "Tucson",
  "Virginia Beach",
  "Washington",
  "Wichita",
  "Other",
];

export const usStatesOptions = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Other",
];

export const ethnicityOptions = [
  "African American",
  "East/Southeast Asian",
  "South Asian",
  "Caucasian",
  "Hispanic",
  "Native American",
  "Pacific Islander",
  "Middle Eastern",
  "Latino",
  "Mixed",
];

export const genderOptions = [
  "Male",
  "Female",
  "Non-binary",
  "Other",
  "Prefer not to say",
];

export const sexualityOptions = [
  "Heterosexual",
  "Bisexual",
  "Homosexual",
  "Other",
  "Prefer not to say",
];
